app/stream/urls.py
from . import views
from . views import (
    VideoDetailView,
    UserVideoListView,
    GeneralVideoListView,
    VideoDeleteView,
)
from django.urls import path
from stream import views as stream_views
from django.contrib.auth import views as auth_views

app_name = "stream"

urlpatterns = [

    path('video/<int:pk>/', VideoDetailView.as_view(), name="video-detail"),
    path('video/<int:pk>/record/', stream_views.record_filled_video, name="video-record-filled"),
    path('video/<int:pk>/upload/', stream_views.upload_filled_video, name="video-upload-filled"),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name="video-delete"),
    path('user/<str:username>', UserVideoListView.as_view(), name="user-videos"),
    path('video/new/',stream_views.create_video, name="video-create"),
    path('video/new',stream_views.upload_video, name="video-upload"),
    path('search',views.search,name="search"),
    path('',views.home,name="home"),
    path('video',GeneralVideoListView.as_view(), name="video-list"),
    path('contact',views.friendRequest,name="contact"),
    path('request-video',views.request_video,name="request-video"),

    path('profile',stream_views.profile, name="profile"),
    path('register/',stream_views.register, name="register"),
    path('login', auth_views.LoginView.as_view(template_name='stream/login.html'), name="login"),
    path('logout',auth_views.LogoutView.as_view(template_name='stream/logout.html'), name="logout"),
    path('setting',stream_views.settings, name="setting"),
    path('theme',stream_views.settings, name="theme"),
    path('notifications',stream_views.notifications, name="notifications"),

    path('forget-password/', stream_views.password_reset, name='forget-password'),
    path('security-answer/<str:username>', stream_views.security_answer, name='security-answer'),
    path('password_reset_done/<str:username>', stream_views.password_reset_done, name='password_reset_done'),
]

app/video_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',include('stream.urls')),

    # note the override comes before the admin URLs below
    path('admin/logout/', auth_views.LogoutView.as_view(template_name='stream/logout.html')),
    path('admin/', admin.site.urls, name="admin"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/stream/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, DeleteView, UpdateView, ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth import logout, authenticate, login
from django.dispatch import Signal
from django.db.models import Q
from django.core.files.base import ContentFile
from django.conf import settings as aws_settings
import os, subprocess, base64, boto3, time, requests, difflib, re
from stream.storage_backends import MediaStorage, ProfilePictureStorage
from . models import VidRequest, VidStream, Contact, FriendRequest, Post, Profile, UserInfo, Notification, Setting
from . forms import VidUploadForm, VidCreateForm, VidRequestForm, UserRegistrationForm, UserUpdateForm, UserInfoUpdateForm, UserProfileUpdateForm, UserProfileUpdateForm,  ValidatingPasswordChangeForm, AddContactForm, UserPermissionForm, VidRecFilledForm, VidUpFilledForm, SecurityQuestionForm, ResetPasswordForm
# from django.http import HttpResponse

class VideoDetailView(DetailView):
    template_name = "stream/video-detail.html"
    model = Post

class GeneralVideoListView(ListView):
    model = Post
    template_name = 'stream/video-list.html'
    context_object_name = 'videos'
    ordering = ['-sendtime']


def search(request):
    if request.method == "POST":
        query = request.POST.get('title', None)
        if query:
            results = Post.objects.filter(title__contains=query)
            return render(request, 'stream/search.html',{'videos':results})

    return render(request, 'stream/search.html')


def home(request):
    return render(request, 'stream/home.html')


def friendRequest(request):
    users = None  # To avoid error if users is not defined
    if request.method == "POST":
        addcontactform = AddContactForm(request.user, request.POST)
        if addcontactform.is_valid():
            add_contact = addcontactform.save(commit=False)
            add_contact.sender = request.user
            add_contact.save()
            # link recent created friendRequest from friend request table to Notification table
            recentFriendRequest = FriendRequest.objects.filter(sender=request.user).last()
            Notification.objects.create(user=request.user, message=f'You have sent a friend request to '+ str(addcontactform.cleaned_data['receiver']) +'.', type=1, friendRequest_id=recentFriendRequest, is_read=True)
            Notification.objects.create(user=addcontactform.cleaned_data['receiver'], message=f'You have received a friend request from '+ str(request.user) +'.', type=2, friendRequest_id=recentFriendRequest)
            return redirect("stream:notifications")
    else:
        addcontactform = AddContactForm(request.user)
        search_query = request.GET.get('search', '')
        # Existing users show in alphabetical order
        users = User.objects.filter(Q(username__icontains=search_query) & ~Q(id=request.user.id) & ~Q(requests_sender__receiver=request.user, requests_sender__status=1) & ~Q(requests_receiver__sender=request.user) & ~Q(contact_sender__receiver=request.user) & ~Q(contact_receiver__sender=request.user) & ~Q(userinfo__permission=request.user.userinfo.permission) & ~Q(userinfo__permission=3)).order_by('username')

    context = {
        'addcontactform': addcontactform,
        'users': users,
    }
    return render(request, 'stream/contact.html', context)


def request_video(request):
    if request.method == "POST":
        requestvideoform = VidRequestForm(request.user, request.POST)
        if requestvideoform.is_valid():
            description = requestvideoform.cleaned_data['description']
            due_date = requestvideoform.cleaned_data['due_date']

            request_video = requestvideoform.save(commit=False)
            request_video.sender = request.user
            request_video.save()
            # link recent created video request from VidRequest table to Notification table
            recentVideoRequest = VidRequest.objects.filter(sender=request.user).last()
            Notification.objects.create(user=request.user, message=f'You have sent a video request to '+ str(requestvideoform.cleaned_data['receiver']) + '.' + '\n\n&nbsp;&nbsp; Video Request ID: ' + str(recentVideoRequest) + '\n&nbsp;&nbsp; Description: ' + description + '\n&nbsp;&nbsp; Due DateTime: ' + due_date.strftime('%Y-%m-%d %H:%M:%S'), type=3, videoRequest_id=recentVideoRequest)
            Notification.objects.create(user=requestvideoform.cleaned_data['receiver'], message=f'You have received a video request from '+ str(request.user) + '.' + '\n\n&nbsp; Video Request ID: ' + str(recentVideoRequest) + '\n&nbsp; Description: ' + description + '\n&nbsp; Due DateTime: ' + due_date.strftime('%Y-%m-%d %H:%M:%S'), type=4, videoRequest_id=recentVideoRequest)
            return redirect('stream:notifications')
    else:
        requestvideoform = VidRequestForm(request.user)

    context = {
        'requestvideoform': requestvideoform
    }
    return render(request, 'stream/request-video.html', context)


def create_video(request):
    if request.method == "POST":
        createvideoform = VidCreateForm(request.user, request.POST, request.FILES)
        if createvideoform.is_valid():
            request_id = createvideoform.cleaned_data['request_id']

            upload_video = createvideoform.save(commit=False)
            upload_video.sender = request.user
            receiverfilter = User.objects.get(username=VidRequest.objects.get(id=request_id.id).sender)
            upload_video.receiver = receiverfilter

            # Decode and save the blob data
            blob_data = request.POST['video_blob']  # Get blob video data from html input
            decoded_data = base64.b64decode(blob_data)  # Convert the video data to 64 byte type
            # upload_video.video.delete(save=False)  # Delete the existing video file
            # upload_video.video.save('video_record.mp4', ContentFile(decoded_data), save=True) # Save into video field with 64 byte content file (video name)

            # Save the video to a temporary file
            temp_video_path = os.path.join(aws_settings.MEDIA_ROOT, 'temp_video.webm')
            with open(temp_video_path, 'wb') as f:
                f.write(decoded_data)

            video_key = f"video_record.mp4"  # video record file name

            # Define the output file path
            output_video_path = os.path.join(aws_settings.MEDIA_ROOT, video_key)

            # Convert webm to mp4 using ffmpeg
            try:
                ffmpeg_path = '/opt/ffmpeg/ffmpeg-6.1-amd64-static/ffmpeg'  # FFMPEG path for Elastic Beanstalk (Path referenced from .ebextensions/ffmpeg.config)
                subprocess.run([ffmpeg_path, '-i', temp_video_path, '-c', 'copy', output_video_path], check=True)
                # subprocess.run(['ffmpeg', '-i', temp_video_path, '-c', 'copy', output_video_path], check=True) # local FFMPEG, make sure to have FFMPEG path setup on your computer
            except subprocess.CalledProcessError as e:
                print(f"FFMPEG Error: {e}")
            # Clean up the temporary file
            os.remove(temp_video_path)

            # Upload video to the input S3 bucket
            s3_client = boto3.client(
                's3',
                aws_access_key_id=aws_settings.AWS_ACCESS_KEY_ID,
                aws_secret_access_key=aws_settings.AWS_SECRET_ACCESS_KEY,
                aws_session_token=aws_settings.AWS_SESSION_TOKEN,
                region_name=aws_settings.AWS_S3_REGION_NAME
            )

            if request.POST.get('blurFace') == 'on':  # Check if the checkbox is checked
                s3_bucket_name = aws_settings.AWS_S3_INPUT_BUCKET_NAME  # input s3 bucket for blur face
            else:
                s3_bucket_name = aws_settings.AWS_STORAGE_BUCKET_NAME   # normal output s3 bucket for storage video

            media_storage = MediaStorage()
            video_name = media_storage.get_available_name(name=video_key)   # Check if file exists, if exists increment file name

            with open(output_video_path, 'rb') as video_file:
                s3_client.upload_fileobj(video_file, s3_bucket_name, video_name)    # store the web record converted mp4 to s3

            # Remove the local converted file
            os.remove(output_video_path)

            # Get the URL of the processed video
            processed_video_url = f'https://{aws_settings.CLOUDFRONT_DOMAIN}/{video_name}'

            upload_video.video = processed_video_url    # store cloudfront video url

            upload_video.save()

            # link recent uploaded video request from Post table to Notification table
            recentVideoUpload = Post.objects.filter(sender=request.user).last()

            Notification.objects.create(user=request.user, message=f'You have post a video to '+ str(receiverfilter) +'.', type=5, post_id=recentVideoUpload)
            Notification.objects.create(user=receiverfilter, message=f'You have received a video post from '+ str(request.user) +'.', type=6, post_id=recentVideoUpload)
            return redirect('stream:video-list')

    else:
        createvideoform = VidCreateForm(request.user)

    context = {
        'createvideoform': createvideoform,
        'notification': Notification.objects.filter(user=request.user, type=4)
    }
    return render(request, 'stream/video-create.html', context)

# Function for wait file to finish upload on s3
def wait_for_file_existence(file_url, max_attempts=60, delay=5):
    """
    Function to wait until a file exists in CloudFront distribution.

    Args:
    - file_url: The URL of the file in CloudFront distribution.

app/stream/templates/stream/base.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Vnonymous</title>
    <link rel="stylesheet" href= "{%static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/logoutUI.css' %}" rel="stylesheet">
    <link href="{% static 'css/styleTopBar.css' %}" rel="stylesheet">
    <style>
      .badge {
        display: inline-block;
        min-width: 10px;
        padding: 3px 7px;
        font-size: 12px;
        font-weight: 700;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        background-color: #f00;
        border-radius: 10px;
      }
    </style>
  </head>
    <!--style in body change the website side background-->
  <body id="page-top" data-bs-spy="scroll" data-bs-target="#mainNav" data-bs-offset="77" style="background-size: cover; background-image: url(' {% static 'assets/img/intro-bg.jpg' %} ');">
    <nav class="navbar navbar-expand-md fixed-top navbar-light" id="mainNav">
      <div class="container"><a class="navbar-brand" href=" {% url 'stream:home' %} " id="Home Button">
          Vnonymous
        </a><button data-bs-toggle="collapse" class="navbar-toggler navbar-toggler-right" data-bs-target="#navbarResponsive" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" value="Menu"><i class="fa fa-bars"></i></button>
          <div class="navbar" id="navbarResponsive">
              <ul class="navbar-nav ms-auto">
                  {% if user.is_authenticated %}
                  <div class="dropdown">
                      <li class="nav-item nav-link">
                          <button class="nav-link active">
                              <a id="Videos Hover">
                                  VIDEOS
                                  &#9660;
                              </a>
                          </button>
                      </li>
                      <div class="dropdown-content">
                        <li class="nav-item nav-link"><a class="nav-link active" href=" {% url 'stream:video-list' %} " id="Video Button">View Videos</a></li>
                        {% if user.userinfo.permission == 1 or user.is_superuser %}
                         <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:video-create' %}" id="New Video Button">Send Video</a>
                        {% endif %}
                        {% if user.userinfo.permission == 2 or user.is_superuser %}
                          <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:request-video' %}" id="Video Request Button">Request Video</a>
                        {% endif %}
                      </div>
                    </div>
                    <li class="nav-item nav-link"><a class="nav-link active" href=" {% url 'stream:contact' %} " id="Add Contacts Button">Add Contacts</a></li>
                    <li class="nav-item nav-link">
                      <a class="nav-link active" href="{% url 'stream:notifications' %}" id="Notification-Button">
                          Notifications
                          {% if unread_notifications_count > 0 %}
                              <span class="badge">{{ unread_notifications_count }}</span>
                          {% endif %}
                      </a>
                  </li>
                    <div class="dropdown">
                      <li class="nav-item nav-link">
                        <button class="nav-link active">
                            <a id="User Hover">
                                <img class="rounded-circle border-dark" src="{{ user.profile.image.url }}" style="border-color: red;" width="25" height="25">
                            &#9660;
                            </a>
                        </button>
                      </li>
                      <div class="dropdown-content">
                          <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:profile' %}" id="Profile Button">Profile</a>
                          <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:setting' %}" id="Setting Button">Settings</a>
                          {% if user.is_superuser %}
                              <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'admin:index' %}" id="Admin Button">Admin</a>
                          {% endif %}
                          <li class="nav-item nav-link"><a class="nav-link active"  href='#'onclick='overlay()' id="Logout Button">Logout</a>
                      </div>
                    </div>
                  {% else %}
                      <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:login' %}" id="Login Button">Login</a></li>
                      <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:register' %}" id="Register Button">Register</a></li>
                  {% endif %}
              </ul>
          </div>
      </div>
  </nav>

    <!-- Page Content -->
    <div class="container" id="app">

        {% block content %}
        {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <div class="map-clean"></div>
    <script src=" {% static 'assets/bootstrap/js/bootstrap.min.js' %} "></script>

    <!-- This js makes the header change to black colour when scrolling -->
    <script src=" {% static 'assets/js/grayscale.js' %} "></script>

    <!-- Logout popup UI -->
    <script src=" {% static 'assets/js/logoutUI.js'%} "></script>
    <script>
        document.getElementById("logout").onclick = function () {
            location.href = "{% url 'stream:logout' %}";
        };
        document.getElementById("cancel").onclick = function () {
          // cancel the pop up and stay on the same page
          overlay();
        };
    </script>

  </body>
</html>

app/stream/templates/stream/home.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Vnonymous</title>
    <link rel="stylesheet" href= "{%static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/styleTopBar.css' %}">
    <link rel="stylesheet" href="{%static 'assets/fonts/font-awesome.min.css' %}">
    <link href="{% static 'css/logoutUI.css' %}" rel="stylesheet">
    <style>
        .badge {
          display: inline-block;
          min-width: 10px;
          padding: 3px 7px;
          font-size: 12px;
          font-weight: 700;
          line-height: 1;
          color: #fff;
          text-align: center;
          white-space: nowrap;
          vertical-align: baseline;
          background-color: #f00;
          border-radius: 10px;
        }
      </style>
</head>

<body id="page-top" data-bs-spy="scroll" data-bs-target="#mainNav" data-bs-offset="77">
    <nav class="navbar navbar-expand-md fixed-top navbar-light" id="mainNav">
        <div class="container"><a class="navbar-brand" href=" {% url 'stream:home' %} " id="Home Button">
            Vnonymous
          </a><button data-bs-toggle="collapse" class="navbar-toggler navbar-toggler-right" data-bs-target="#navbarResponsive" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" value="Menu"><i class="fa fa-bars"></i></button>
            <div class="navbar" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <div class="dropdown">
                        <li class="nav-item nav-link">
                            <button class="nav-link active">
                                <a id="Videos Hover">
                                    VIDEOS &#9660;
                                </a>
                            </button>
                        </li>
                        <div class="dropdown-content">
                            <li class="nav-item nav-link"><a class="nav-link active" href=" {% url 'stream:video-list' %} " id="Video Button">View Videos</a></li>
                            {% if user.userinfo.permission == 1 or user.is_superuser %}
                                <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:video-create' %}" id="New Video Button">Send Video</a>
                            {% endif %}
                            {% if user.userinfo.permission == 2 or user.is_superuser %}
                                 <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:request-video' %}" id="Video Request Button">Request Video</a>
                            {% endif %}
                        </div>
                      </div>
                      <li class="nav-item nav-link"><a class="nav-link active" href=" {% url 'stream:contact' %} " id="Add Contacts Button">Add Contacts</a></li>
                      <li class="nav-item nav-link">
                        <a class="nav-link active" href="{% url 'stream:notifications' %}" id="Notification-Button">
                            Notifications
                            {% if unread_notifications_count > 0 %}
                                <span class="badge badge-light">{{ unread_notifications_count }}</span>
                            {% endif %}
                        </a>
                      </li>
                      <div class="dropdown">
                        <li class="nav-item nav-link">
                        <button class="nav-link active">
                            <a id="User Hover">
                                <img class="rounded-circle border-dark" src="{{ user.profile.image.url }}" style="border-color: red;" width="25" height="25">
                            &#9660;
                            </a>
                        </button>
                        </li>
                        <div class="dropdown-content">
                            <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:profile' %}" id="Profile Button">Profile</a>
                            <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:setting' %}" id="Setting Button">Settings</a>
                            {% if user.is_superuser %}
                                <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'admin:index' %}" id="Admin Button">Admin</a>
                            {% endif %}
                            <li class="nav-item nav-link"><a class="nav-link active"  href='#'onclick='overlay()' id="Logout Button">Logout</a>
                        </div>
                      </div>
                    {% else %}
                        <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:login' %}" id="Login Button">Login</a></li>
                        <li class="nav-item nav-link"><a class="nav-link active" href="{% url 'stream:register' %}" id="Register Button">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% if user.is_authenticated %}
        <div id="overlay" class="float-center" style="position:fixed; top:30%;">
            <div>
                <p class="text-dark">Are you sure you want to logout?</p>
                <button id="logout" class="float-left submit-button me-1">Logout</button>
                <button id="cancel" class="float-left submit-button">Cancel</button>
            </div>
        </div>
    {% endif %}

    <header class="masthead" style="background-image:url('{% static 'assets/img/intro-bg.jpg' %}');">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h1 class="brand-heading">Vnonymous</h1>
                        <p class="intro-text">Share Unseen, Connect Unheard: Your Video Stories, Your Way!</p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section class="text-center content-section" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>About Vnonymous</h2>
                    <p>Vnonymous is the ultimate destination for those who crave privacy and self-expression in the world of video sharing. With Vnonymous, you can send and receive videos anonymously, allowing you to share your thoughts, experiences, and creativity without revealing your identity.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="text-center download-section content-section" id="download" style="background-image:url(' {% static 'assets/img/downloads-bg.jpg' %} ');">
        <div class="container">
            <div class="col-lg-8 mx-auto">
                <h1>Start trying Vnonymous</h1>
                {% if user.is_authenticated %}
                <p>Start by creating a new video or by adding a new contact</p>
                    <a href=" {% url 'stream:video-create' %}" >
                        <button class="btn btn-primary btn-lg btn-default" type="button" > Visit CREATE Video page</button>
                    </a>
                    <a href=" {% url 'stream:contact' %}">
                        <button class="btn btn-primary btn-lg btn-default" type="button" > Visit ADD Contact page</button>
                    </a>
                {% else %}
                <p>In order to use this, start by creating an account</p>
                <a href=" {% url 'stream:register' %}"><button class="btn btn-primary btn-lg btn-default" type="button" >Visit CREATE ACCOUNT page</button></a>
                {% endif %}

            </div>
        </div>
    </section>
    <div class="map-clean"></div>
    <script src=" {% static 'assets/bootstrap/js/bootstrap.min.js' %} "></script>

    <!-- This js makes the header change to black colour when scrolling -->
    <script src=" {% static 'assets/js/grayscale.js' %} "></script>

    <!-- Logout popup UI -->
    <script src=" {% static 'assets/js/logoutUI.js'%} "></script>
    <script>
        document.getElementById("logout").onclick = function () {
            location.href = "{% url 'stream:logout' %}";
        };
        document.getElementById("cancel").onclick = function () {
            location.href = "{% url 'stream:home' %}";
        };
    </script>

</body>

</html>

app/stream/templates/stream/user_videos.html
{% extends 'stream/base.html'%}
{% block content %}
    {% if user.is_authenticated %}
        <div id="overlay" class="float-center" style="position:fixed; top:30%;">
            <div>
                <p class="text-dark">Are you sure to logout?</p>
                <button id="logout" class="float-left submit-button me-1">Logout</button>
                <button id="cancel" class="float-left submit-button">Cancel</button>
            </div>
        </div>
    {% endif %}
    <div style = "margin-top: 25px; padding-top: 85px; padding-bottom: 20px;">
        <h1>Videos For {{ user }}</h1>
        {% for item in videos %}
            {% if item.sender == user or item.receiver == user %}
                <div class="card mb-3" style="width: 75%; box-shadow: 12em; margin: auto;">
                    <img class="rounded-circle border-dark" src="{{ item.sender.profile.image.url }}" style="border-color: red;" width="50" height="50">
                    <a class="mr-2" href="{% url 'stream:user-videos' item.sender.username %}" style="text-align: start;">{{ item.sender }}</a>
                    <h12 style="text-align: center; margin-top: 0.25em; font-size: 1.25em;">{{ item.sendtime }}</h12>
                    <video class="card-img-top" controls style="width: 100%; height: auto;">
                        {% comment %} <source src="{{ item.video.url }}" type="video/mp4"> {% endcomment %}
                        <source src="{{ item.video }}" type="video/mp4">
                    </video>
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'stream:video-detail' item.id  %}">{{ item.title }}</a></h5>
                        <p class="card-text">{{ item.description }}</p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

app/stream/templates/stream/video-detail.html
{% extends 'stream/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
    <div id="overlay" class="float-center" style="position:fixed; top:30%;">
        <div>
            <p class="text-dark">Are you sure to logout?</p>
            <button id="logout" class="float-left submit-button me-1">Logout</button>
            <button id="cancel" class="float-left submit-button">Cancel</button>
        </div>
    </div>
    {% endif %}
    <div style = "padding-bottom: 60px; padding-top: 125px; ">
        {% if object.sender == user %}
                <div style = "margin-top: 25px; padding-bottom: 25px;">
                    <img class="rounded-circle border-dark" src="{{ object.sender.profile.image.url }}" style="border-color: red;" width="100" height="100">
                    <a style="font-size: 2em; text-align: start; margin: 1em; display:inline; align-items: center;" href="{% url 'stream:user-videos' object.sender.username %}">{{ object.sender.username }}</a>
                </div>
                <a class="btn btn-danger btn-sm mb-4" href="{% url 'stream:video-delete' object.id %}">Delete</a>
        {% endif %}
        <div class="card mb-3" style="width: 75%; box-shadow: 12em; margin: auto;">
            <h12 style="text-align: center; margin-top: 0.25em; font-size: 1.25em;">{{ object.sendtime }}</h12>
            <video class="card-img-top" controls style="width: 100%; height: auto;">
                {% comment %} <source src="{{ object.video.url }}" type="video/mp4"> {% endcomment %}
                <source src="{{ object.video }}" type="video/mp4">
            </video>
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'stream:video-detail' object.id  %}">{{ object.title }}</a></h5>
                <p class="card-text">{{ object.description }}</p>
            </div>
        </div>

    </div>
{% endblock content %}